global:
  scrape_interval: 10s # Coleta m√©tricas a cada 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'hms_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway:9000', 'user-service:8081', 'profile-service:8082', 'appointment-service:8083', 'pharmacy-service:8084' ]
        labels:
          application: 'HMS Microservices'