server:
  port: 8088

spring:
  config:
    import: "optional:classpath:common-application.yml"
  application:
    name: billing-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_billing_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:mysql_billing_user}
    password: ${DB_PASSWORD:mysql_billing_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Padronizado
        format_sql: true
  rabbitmq: # Configurações de conexão Spring padrão
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}
  rabbitmq:
    queues:
      appointment-billing: q.appointment.billing
    exchanges:
      internal: e.internal
    routing-keys:
      appointment-completed: rk.appointment.completed