server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Configuração Global de CORS
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "${FRONTEND_URI}"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      routes:
        # Rota para o User-Service
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - name: TokenFilter

        # Rota para o Profile-Service
        - id: profile-service-route
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - name: TokenFilter

        # Rota para o Appointment-Service
        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
            - Path=/patient/**, /doctor/**, /appointments/**, /records/**, /prescriptions/**, /health-metrics/**, /documents/**, /adverse-effects/**, /admin/**
          filters:
            - name: TokenFilter

        # Rota para o Pharmacy-Service
        - id: pharmacy-service-route
          uri: lb://pharmacy-service
          predicates:
            - Path=/pharmacy/**
          filters:
            - name: TokenFilter

        # Rota para o Media-Service
        - id: media-service-route
          uri: lb://media-service
          predicates:
            - Path=/media/**
          filters:
            - name: TokenFilter

        # Rota para o Chat WebSocket
        - id: chat-websocket-route
          uri: lb:ws://chat-service
          predicates:
            - Path=/chat/ws/**
          filters:
            - RewritePath=/chat/ws/(?<segment>.*), /ws/${segment}
            - name: TokenFilter

              # Rota para o Chat REST
        - id: chat-rest-route
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - name: TokenFilter

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"