server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Filtros padrão aplicados a TODAS as rotas
      default-filters:
        - name: TokenFilter

      server:
        webflux:
          # Configuração de CORS Global
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600

          # Lista de rotas (nova sintaxe)
          routes:
            # Rota para o User-Service
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/auth/**, /users/**

            # Rota para o Profile-Service
            - id: profile-service-route
              uri: lb://profile-service
              predicates:
                - Path=/profile/**

            # Rota para o Appointment-Service
            - id: appointment-service-route
              uri: lb://appointment-service
              predicates:
                - Path=/patient/**, /doctor/**, /appointments/**, /records/**, /prescriptions/**, /health-metrics/**, /documents/**, /adverse-effects/**, /admin/**

            # Rota para o Pharmacy-Service
            - id: pharmacy-service-route
              uri: lb://pharmacy-service
              predicates:
                - Path=/pharmacy/**

            # Rota para o Media-Service
            - id: media-service-route
              uri: lb://media-service
              predicates:
                - Path=/media/**

            # Rota para o Chat-Service (REST + WebSocket)
            - id: chat-service-route
              uri: lb://chat-service
              predicates:
                - Path=/chat/**, /ws/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

application:
  security:
    jwt:
      secret-key: NERVZW5jb2RlIG9ubGluZSIgY29tIHBlbG8gbWVub3MgMjU2IGJpdHMuMjU2IGJpdHMuMjU2IGJpdHMuMjU2IGJpdHMu

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost