server:
  port: ${SERVER_PORT:8083}

services:
  profile:
    base-url: "${PROFILE_URI:http://localhost:8082}"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_appointment_db}
    username: ${DB_USER:mysql_appointment_user}
    password: ${DB_PASSWORD:mysql_appointment_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

application:
  rabbitmq:
    exchange: internal.exchange
    prescription-issued-routing-key: prescription.issued
    appointment-status-routing-key: appointment.status.changed
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # URL do container Zipkin