server:
  port: ${SERVER_PORT:8081}

services:
  profile:
    base-url: "${PROFILE_URI:http://localhost:8082}"

spring:
  application:
    name: user-service
    rabbitmq:
      exchange: internal.exchange
      user-created-routing-key: user.event.created
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_user_db}
    username: ${DB_USER:mysql_user}
    password: ${DB_PASSWORD:mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
